export const PEOPLE_LOADING = "PEOPLE_LOADING";
export const PEOPLE_LOADED = "PEOPLE_LOADED";
export const PERSON_LOADING = "PERSON_LOADING";
export const PERSON_LOADED = "PERSON_LOADED";

export const MOVIES_LOADING = "MOVIES_LOADING";
export const MOVIES_LOADED = "MOVIES_LOADED";
export const MOVIE_LOADING = "MOVIE_LOADING";
export const MOVIE_LOADED = "MOVIE_LOADED";

export const PLANETS_LOADING = "PLANETS_LOADING";
export const PLANETS_LOADED = "PLANETS_LOADED";
export const PLANET_LOADING = "PLANET_LOADING";
export const PLANET_LOADED = "PLANET_LOADED";